---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Applications/Applications/application-tutorial/tutorial/1.0.0
  type: udm.DeploymentPackage
  deployables:
  - name: tutorial-deployment
    type: k8s.DeploymentSpec
    containers:
    - name: tutorial-container
      type: k8s.ContainerSpec
      containerName: tutorial-container
      image: lyhsoft/tutorial:113
      ports:
      - name: tutorial-container-port
        type: k8s.ContainerPortSpec
        containerPort: "1234"
    labels:
      app: tutorial
    deploymentName: tutorial-deployment
    replicasCount: "1"
    matchLabels:
      app: tutorial
  - name: tutorial-service
    type: k8s.ServiceSpec
    serviceName: tutorial-service
    serviceType: LoadBalancer
    selectors:
      app: tutorial
    ports:
    - name: tutorial-service-port
      type: k8s.ServicePortSpec
      portName: http
      port: "80"
      targetPort: "1234"